name: meowlish
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  country_pickers: ^2.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_svg_provider: any
  grouped_list: ^5.1.2
  readmore: ^2.2.0
  easy_date_timeline: ^1.0.2
  intl: ^0.18.0
  image_picker: ^0.8.4+4
  jwt_decode: ^0.3.1
  email_otp: any
  sms_autofill: ^2.3.0
  shared_preferences: ^2.2.2
  dio: ^4.0.0
  url_launcher: ^6.0.9
  awesome_dialog: ^3.1.0
  video_player: ^2.8.2

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Jost
      fonts: 
        - asset: assets/fonts/JostSemiBold.ttf
          weight: 600
        - asset: assets/fonts/JostBold.ttf
          weight: 700
    - family: Mulish
      fonts: 
        - asset: assets/fonts/MulishBold.ttf
          weight: 700
        - asset: assets/fonts/MulishExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MulishItalicExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MulishSemiBold.ttf
          weight: 600
    - family: Jua
      fonts: 
        - asset: assets/fonts/JuaRegular.ttf
          weight: 400
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Mishella
      fonts: 
        - asset: assets/fonts/Mishella.ttf
          weight: 400
    - family: Helena Johnsmith
      fonts: 
        - asset: assets/fonts/HelenaJohnsmithRegular.ttf
          weight: 400
